Added documentation for armv8hf and a dependency check.

diff --git a/armbian2gentoo b/armbian2gentoo
--- a/armbian2gentoo
+++ b/armbian2gentoo
@@ -6,6 +6,18 @@ COPYRIGHT="Copyright (C) 2017 Nathan Shearer"
 LICENSE="GNU General Public License 2.0"
 VERSION="0.0.0.0"
 
+# \brief Ensures dependencies are present
+# \param $@ The dependencies to check for
+function armbian2gentoo_check_dependencies
+{
+	for TOOL in "$@"; do
+		if ! type "$TOOL" >/dev/null 2>/dev/null; then
+			echo "$CODENAME: \"$TOOL\" is required for this application to work correctly." >&2
+			exit
+		fi
+	done
+}
+
 # \brief Find the root file system
 # \param $1 The image file to scan
 function armbian2gentoo_findroot
@@ -62,6 +74,7 @@ function armbian2gentoo_help
 	echo "  $CODENAME -i https://dl.armbian.com/orangepipc/Ubuntu_xenial_default.7z -o orangepipc.img"
 	echo "  $CODENAME -i https://dl.armbian.com/orangepipc2/Ubuntu_xenial_dev_nightly.7z -o orangepipc2.img"
 	echo "  $CODENAME -i https://dl.armbian.com/pine64/Ubuntu_xenial_dev_nightly.7z -o pine64.img"
+	echo "  $CODENAME -a armv8hf -i https://dl.armbian.com/orangepipc2/Debian_stretch_next.7z -p stage3download,stage3hash,extract,dynamictranslation,deletestage3,resolvconf,mountchroot,portage,timezone,locale,password -o orangepipc2.img"
 	echo
 	echo "Version:"
 	echo "  $NAME $VERSION"
@@ -74,6 +87,10 @@ function armbian2gentoo_main
 {
 	echo "Downloading the armbian image..."
 	wget -q --show-progress "$ARMBIAN_URL" -O "$TMP/armbian.7z"
+	if [ $? -ne 0 ]; then
+		echo "error: downloading armbian image failed"
+		exit 1
+	fi
 	echo -n "Extracting the armbian image..."
 	7z x -o"$TMP/" "$TMP/armbian.7z" >/dev/null
 	echo " done."
@@ -98,7 +115,7 @@ function armbian2gentoo_main
 	mv "$TMP"/root/* "$TMP"/root/.oldroot
 	echo " done."
 	
-	./gentooinstall -a "$ARCHITECTURE" -d "$TMP"/root $PHASES
+	gentooinstall -a "$ARCHITECTURE" -d "$TMP"/root $PHASES
 	if [ $? -ne 0 ]; then
 		echo "error: gentooinstall failed"
 		echo "temporary files at \"$TMP\" have not been deleted"
@@ -184,6 +201,7 @@ done
 # prepare environment
 #
 
+armbian2gentoo_check_dependencies 7z gentooinstall parted
 TMP="$TMP/$CODENAME.$$"
 mkdir -p "$TMP"
 
