Automatically detect the boot device

diff --git a/gentooinstall b/gentooinstall
--- a/gentooinstall
+++ b/gentooinstall
@@ -4,7 +4,7 @@ NAME="Gentoo Install"
 CODENAME="gentooinstall"
 COPYRIGHT="Copyright (C) 2016 Nathan Shearer"
 LICENSE="GNU General Public License 2.0"
-VERSION="1.0.0.0"
+VERSION="1.1.0.0"
 
 function gentooinstall_architecture
 {
@@ -59,6 +59,30 @@ function gentooinstall_check_dependencies
 			exit
 		fi
 	done
+}
+
+# \brief Attempt to detect the boot device
+function gentooinstall_detect_boot_device
+{
+	gentooinstall_check_dependencies findmnt lsblk
+
+	if [ "$DEVICE" = "/tmp/none" ]; then
+		local BOOT_PARTITION=$(findmnt -n -P "$DESTINATION/boot" | sed -r -e 's/.*SOURCE="([^"]+)".*/\1/')
+		#echo "Found \"$BOOT_PARTITION\" mounted at \"$DESTINATION/boot\""
+		local BOOT_PARTITION_BASENAME=$(basename "$BOOT_PARTITION")
+		local BOOT_PARTITION_DIRNAME=$(dirname "$BOOT_PARTITION")
+		local DEVICE_DETECTED_BASENAME=$(lsblk -n -P -s | grep -A 1 "$BOOT_PARTITION_BASENAME" | tail -n 1 | sed -r -e 's/.*NAME="([^"]+)".*/\1/')
+		DEVICE_DETECTED="$BOOT_PARTITION_DIRNAME/$DEVICE_DETECTED_BASENAME"
+		#echo "Detected boot device: $DEVICE_DETECTED"
+		if [ -b "$DEVICE_DETECTED" ]; then
+			DEVICE="$DEVICE_DETECTED"
+		else
+			echo "Found \"$BOOT_PARTITION\" mounted at \"$DESTINATION/boot\""
+			echo "Detected boot device: $DEVICE_DETECTED"
+			echo "error: \"$DEVICE_DETECTED\" is not a block device"
+			return 1
+		fi
+	fi
 }
 
 # \brief Displays the help and exits the program
@@ -193,16 +217,16 @@ function gentooinstall_main
 
 function gentooinstall_phase_bootloader
 {
+	gentooinstall_detect_boot_device
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+
 	if $CHROOT; then
 		gentooinstall_quiet env-update
 		source /etc/profile
 		
 		echo "Starting the bootloader phase..."
-
-		if [ ! -b "$DEVICE" ]; then
-			echo "error: \"$DEVICE\" is not a block device"
-			return 1
-		fi
 
 		emerge -uq sys-boot/lilo
 
@@ -240,7 +264,7 @@ function gentooinstall_phase_bootloader
 		# some hard drives use characters in their id that causes lilo to break when using boot=/dev/disk/by-id
 		# this symlink is a workaround for that problem
 		BOOTBYID=$(find -L /dev/disk/by-id -samefile "$DEVICE" | head -n 1)
-		ln -s "$BOOTBYID" /etc/lilo.conf.boot
+		ln -f -s "$BOOTBYID" /etc/lilo.conf.boot
 
 		echo "default=$KERNEL_FILENAME" >/etc/lilo.conf
 		echo "prompt" >>/etc/lilo.conf
@@ -250,7 +274,7 @@ function gentooinstall_phase_bootloader
 		echo "	label=$KERNEL_FILENAME" >>/etc/lilo.conf
 		echo "	append=\"root=PARTUUID=$ROOTPARTUUID rootwait\"" >>/etc/lilo.conf
 
-		lilo
+		gentooinstall_quiet lilo
 	else
 		cp -f "$THIS" "$DESTINATION/tmp"
 		$CHROOTARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase bootloader -b "$DEVICE"
@@ -425,22 +449,22 @@ function gentooinstall_phase_extract
 
 function gentooinstall_phase_fstab
 {
+	gentooinstall_detect_boot_device
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+	
 	if $CHROOT; then
 		gentooinstall_quiet env-update
 		source /etc/profile
 		
 		echo -n "Updating /etc/fstab... "
 		
-		if [ ! -b "$DEVICE" ]; then
-			echo "error: \"$DEVICE\" is not a block device"
-			return 1
-		fi
-		
 		local BOOTUUID=$(lsblk -f -n -o UUID "$DEVICE"*1)
 		local ROOTUUID=$(lsblk -f -n -o UUID "$DEVICE"*2)
 		local SWAPUUID=$(lsblk -f -n -o UUID "$DEVICE"*3)
 		
-		mv /etc/fstab /etc/fstab.example
+		mv -n /etc/fstab /etc/fstab.example
 		echo "# <fs>  <mountpoint>  <type>  <opts>  <dump/pass>" >>/etc/fstab
 		echo "UUID=$BOOTUUID  /boot  vfat  noauto,noatime  0 0" >>/etc/fstab
 		echo "UUID=$ROOTUUID  /  ext4  noatime  0 1" >>/etc/fstab
