Added uefi-refind bootloader Removed unused code from the kernel phase

diff --git a/gentooinstall b/gentooinstall
--- a/gentooinstall
+++ b/gentooinstall
@@ -4,7 +4,7 @@ NAME="Gentoo Install"
 CODENAME="gentooinstall"
 COPYRIGHT="Copyright (C) 2016 Nathan Shearer"
 LICENSE="GNU General Public License 2.0"
-VERSION="1.1.0.0"
+VERSION="1.2.0.0"
 
 function gentooinstall_architecture
 {
@@ -109,6 +109,10 @@ function gentooinstall_help
 	echo "    The block size used for alignment."
 	echo "  --block-device-partition-type gpt"
 	echo "    The type of a partition table to create: gpt or msdos."
+	echo "  --bootloader bios-lilo"
+	echo "    Which bootloader to install on the boot device:"
+	echo "      bios-lilo"
+	echo "      uefi-refind"
 	echo "  --chroot false"
 	echo "    Used internally to chroot into the destination directory for some phases."
 	echo "  -d, --destination /mnt/gentoo"
@@ -217,6 +221,28 @@ function gentooinstall_main
 
 function gentooinstall_phase_bootloader
 {
+	case "$BOOTLOADER" in
+		"bios-lilo")
+			gentooinstall_phase_bootloader_bios_lilo
+			if [ $? -ne 0 ]; then
+				return 1
+			fi
+			;;
+		"uefi-refind")
+			gentooinstall_phase_bootloader_uefi_refind
+			if [ $? -ne 0 ]; then
+				return 1
+			fi
+			;;
+		*)
+			echo "error: unsupported bootloader \"$BOOTLOADER\""
+			return 1
+			;;
+	esac
+}
+
+function gentooinstall_phase_bootloader_bios_lilo
+{
 	gentooinstall_detect_boot_device
 	if [ $? -ne 0 ]; then
 		return 1
@@ -226,7 +252,7 @@ function gentooinstall_phase_bootloader
 		gentooinstall_quiet env-update
 		source /etc/profile
 		
-		echo "Starting the bootloader phase..."
+		echo "Installing the lilo bootloader..."
 
 		emerge -uq sys-boot/lilo
 
@@ -238,7 +264,7 @@ function gentooinstall_phase_bootloader
 		KERNEL_VERSION=$(grep ^VERSION /usr/src/linux/Makefile | sed -r 's/VERSION *= *//')
 		KERNEL_PATCHLEVEL=$(grep ^PATCHLEVEL /usr/src/linux/Makefile | sed -r 's/PATCHLEVEL *= *//')
 		KERNEL_SUBLEVEL=$(grep ^SUBLEVEL /usr/src/linux/Makefile | sed -r 's/SUBLEVEL *= *//')
-		KERNEL_EXTRAVERSION=$(grep ^EXTRAVERSION /usr/src/linux/Makefile | sed -r 's/EXTRAVERSION *= *//')
+		KERNEL_EXTRAVERSION=$(grep ^EXTRAVERSION /usr/src/linux/Makefile | sed -r 's/EXTRAVERSION *= *-*//')
 
 		KERNEL="/usr/src/linux/arch/$ARCHITECTURE/boot/bzImage"
 		if [ ! -f "$KERNEL" ]; then
@@ -277,7 +303,70 @@ function gentooinstall_phase_bootloader
 		gentooinstall_quiet lilo
 	else
 		cp -f "$THIS" "$DESTINATION/tmp"
-		$CHROOTARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase bootloader -b "$DEVICE"
+		$CHROOTARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase bootloader --bootloader "$BOOTLOADER" -b "$DEVICE"
+	fi
+}
+
+function gentooinstall_phase_bootloader_uefi_refind
+{
+	gentooinstall_detect_boot_device
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+
+	if $CHROOT; then
+		gentooinstall_quiet env-update
+		source /etc/profile
+		
+		echo "Installing the rEFInd bootloader..."
+
+		emerge -uq sys-boot/refind
+
+		KERNEL_MAKEFILE="/usr/src/linux/Makefile"
+		if [ ! -f "$KERNEL_MAKEFILE" ]; then
+			echo "error: A kernel makefile was not found at \"$KERNEL_MAKEFILE\""
+			return 1
+		fi
+		KERNEL_VERSION=$(grep ^VERSION /usr/src/linux/Makefile | sed -r 's/VERSION *= *//')
+		KERNEL_PATCHLEVEL=$(grep ^PATCHLEVEL /usr/src/linux/Makefile | sed -r 's/PATCHLEVEL *= *//')
+		KERNEL_SUBLEVEL=$(grep ^SUBLEVEL /usr/src/linux/Makefile | sed -r 's/SUBLEVEL *= *//')
+		KERNEL_EXTRAVERSION=$(grep ^EXTRAVERSION /usr/src/linux/Makefile | sed -r 's/EXTRAVERSION *= *-*//')
+
+		KERNEL="/usr/src/linux/arch/$ARCHITECTURE/boot/bzImage"
+		if [ ! -f "$KERNEL" ]; then
+			echo "error: A kernel was not found at \"$KERNEL\""
+			return 1
+		fi
+
+		KERNEL_FILENAME="vmlinuz-$KERNEL_VERSION"
+		if [ "$KERNEL_PATCHLEVEL" != "" ]; then
+			KERNEL_FILENAME="$KERNEL_FILENAME.$KERNEL_PATCHLEVEL"
+		fi
+		if [ "$KERNEL_SUBLEVEL" != "" ]; then
+			KERNEL_FILENAME="$KERNEL_FILENAME.$KERNEL_SUBLEVEL"
+		fi
+		if [ "$KERNEL_EXTRAVERSION" != "" ]; then
+			KERNEL_FILENAME="$KERNEL_FILENAME-$KERNEL_EXTRAVERSION"
+		fi
+		cp -f "$KERNEL" "/boot/$KERNEL_FILENAME.efi"
+		KERNEL="$KERNEL_FILENAME.efi"
+
+		ROOTPARTUUID=$(lsblk -f -n -o PARTUUID "$DEVICE"*2)
+
+		refind-install --usedefault "$DEVICE"1
+		
+		local REFIND_CONFIG=$(find /boot -name refind.conf)
+		mv -n "$REFIND_CONFIG" "$REFIND_CONFIG".example
+		local REFIND_OS_ICON=$(find /boot -name os_gentoo.png | sed -r -e 's/\/boot\///')
+		echo "timeout 5" >"$REFIND_CONFIG"
+		echo "menuentry Gentoo {" >>"$REFIND_CONFIG"
+		echo "	icon $REFIND_OS_ICON" >>"$REFIND_CONFIG"
+		echo "	loader $KERNEL" >>"$REFIND_CONFIG"
+		echo "	options \"ro root=PARTUUID=$ROOTPARTUUID rootwait\"" >>"$REFIND_CONFIG"
+		echo "}" >>"$REFIND_CONFIG"
+	else
+		cp -f "$THIS" "$DESTINATION/tmp"
+		$CHROOTARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase bootloader --bootloader "$BOOTLOADER" -b "$DEVICE"
 	fi
 }
 
@@ -486,15 +575,10 @@ function gentooinstall_phase_kernel
 		
 		emerge -q sys-kernel/gentoo-sources
 		cd /usr/src/linux
-		local VERSION=$(grep '^VERSION' Makefile | sed -r 's/[^=]+ = //')
-		local PATCHLEVEL=$(grep '^PATCHLEVEL' Makefile | sed -r 's/[^=]+ = //')
-		local SUBLEVEL=$(grep '^SUBLEVEL' Makefile | sed -r 's/[^=]+ = //')
-		local EXTRAVERSION=$(grep '^EXTRAVERSION' Makefile | sed -r 's/[^=]+ = //')
 		local NAME=$(grep '^NAME' Makefile | sed -r 's/[^=]+ = //')
 		make defconfig
-		KERNEL=$(make -j$THREADS | tee /dev/tty | grep '^Kernel' | sed -r 's/^Kernel: (.*) is ready.*$/\1/')
+		make -j$THREADS
 		make modules_install
-		cp "$KERNEL" /boot/vmlinuz-$VERSION.$PATCHLEVEL.$SUBLEVEL$EXTRAVERSION
 	else
 		cp -f "$THIS" "$DESTINATION/tmp"
 		$CHROOTARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase kernel
@@ -804,6 +888,7 @@ function gentooinstall_quiet
 # default configuration
 
 ARCHITECTURE=$(gentooinstall_architecture)
+BOOTLOADER=bios-lilo
 CHROOT=false
 CHROOTARCH=""
 DEBUG=false
@@ -850,6 +935,10 @@ while [ $# -ne 0 ]; do
 			;;
 		"--block-device-partition-type")
 			DEVICE_PARTITION_TYPE="$2"
+			shift 2
+			;;
+		"--bootloader")
+			BOOTLOADER="$2"
 			shift 2
 			;;
 		"--chroot")
